backend/K22CNT3_NKL_2210900035_Project2/K22CNT3_NKL_2210900035_Project2/Controllers/CHAPTERsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT3_NKL_2210900035_Project2.Models;

namespace K22CNT3_NKL_2210900035_Project2.Controllers
{
    public class CHAPTERsController : Controller
    {
        private K22CNT3_NKL_2210900035_Project2Entities db = new K22CNT3_NKL_2210900035_Project2Entities();

        // GET: CHAPTERs
        public ActionResult Index()
        {
            var cHAPTERs = db.CHAPTERs.Include(c => c.STORY);
            return View(cHAPTERs.ToList());
        }

        // GET: CHAPTERs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CHAPTER cHAPTER = db.CHAPTERs.Find(id);
            if (cHAPTER == null)
            {
                return HttpNotFound();
            }
            return View(cHAPTER);
        }

        // GET: CHAPTERs/Create
        public ActionResult Create()
        {
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen");
            return View();
        }

        // POST: CHAPTERs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ma_chuong,so_chuong,ten_chuong,noi_dung,ngay_dang,ma_truyen")] CHAPTER cHAPTER)
        {
            if (ModelState.IsValid)
            {
                db.CHAPTERs.Add(cHAPTER);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen", cHAPTER.ma_truyen);
            return View(cHAPTER);
        }

        // GET: CHAPTERs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CHAPTER cHAPTER = db.CHAPTERs.Find(id);
            if (cHAPTER == null)
            {
                return HttpNotFound();
            }
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen", cHAPTER.ma_truyen);
            return View(cHAPTER);
        }

        // POST: CHAPTERs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ma_chuong,so_chuong,ten_chuong,noi_dung,ngay_dang,ma_truyen")] CHAPTER cHAPTER)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cHAPTER).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen", cHAPTER.ma_truyen);
            return View(cHAPTER);
        }

        // GET: CHAPTERs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CHAPTER cHAPTER = db.CHAPTERs.Find(id);
            if (cHAPTER == null)
            {
                return HttpNotFound();
            }
            return View(cHAPTER);
        }

        // POST: CHAPTERs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CHAPTER cHAPTER = db.CHAPTERs.Find(id);
            db.CHAPTERs.Remove(cHAPTER);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

backend/K22CNT3_NKL_2210900035_Project2/K22CNT3_NKL_2210900035_Project2/Controllers/COMMENTsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT3_NKL_2210900035_Project2.Models;

namespace K22CNT3_NKL_2210900035_Project2.Controllers
{
    public class COMMENTsController : Controller
    {
        private K22CNT3_NKL_2210900035_Project2Entities db = new K22CNT3_NKL_2210900035_Project2Entities();

        // GET: COMMENTs
        public ActionResult Index()
        {
            var cOMMENTs = db.COMMENTs.Include(c => c.NGUOI_DUNG).Include(c => c.STORY);
            return View(cOMMENTs.ToList());
        }

        // GET: COMMENTs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COMMENT cOMMENT = db.COMMENTs.Find(id);
            if (cOMMENT == null)
            {
                return HttpNotFound();
            }
            return View(cOMMENT);
        }

        // GET: COMMENTs/Create
        public ActionResult Create()
        {
            ViewBag.ma_nguoi_dung = new SelectList(db.NGUOI_DUNG, "ma_nguoi_dung", "ten_dang_nhap");
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen");
            return View();
        }

        // POST: COMMENTs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ma_binh_luan,noi_dung,ngay_binh_luan,ma_nguoi_dung,ma_truyen")] COMMENT cOMMENT)
        {
            if (ModelState.IsValid)
            {
                db.COMMENTs.Add(cOMMENT);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ma_nguoi_dung = new SelectList(db.NGUOI_DUNG, "ma_nguoi_dung", "ten_dang_nhap", cOMMENT.ma_nguoi_dung);
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen", cOMMENT.ma_truyen);
            return View(cOMMENT);
        }

        // GET: COMMENTs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COMMENT cOMMENT = db.COMMENTs.Find(id);
            if (cOMMENT == null)
            {
                return HttpNotFound();
            }
            ViewBag.ma_nguoi_dung = new SelectList(db.NGUOI_DUNG, "ma_nguoi_dung", "ten_dang_nhap", cOMMENT.ma_nguoi_dung);
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen", cOMMENT.ma_truyen);
            return View(cOMMENT);
        }

        // POST: COMMENTs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ma_binh_luan,noi_dung,ngay_binh_luan,ma_nguoi_dung,ma_truyen")] COMMENT cOMMENT)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cOMMENT).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ma_nguoi_dung = new SelectList(db.NGUOI_DUNG, "ma_nguoi_dung", "ten_dang_nhap", cOMMENT.ma_nguoi_dung);
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen", cOMMENT.ma_truyen);
            return View(cOMMENT);
        }

        // GET: COMMENTs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COMMENT cOMMENT = db.COMMENTs.Find(id);
            if (cOMMENT == null)
            {
                return HttpNotFound();
            }
            return View(cOMMENT);
        }

        // POST: COMMENTs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            COMMENT cOMMENT = db.COMMENTs.Find(id);
            db.COMMENTs.Remove(cOMMENT);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

backend/K22CNT3_NKL_2210900035_Project2/K22CNT3_NKL_2210900035_Project2/Controllers/STORiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT3_NKL_2210900035_Project2.Models;

namespace K22CNT3_NKL_2210900035_Project2.Controllers
{
    public class STORiesController : Controller
    {
        private K22CNT3_NKL_2210900035_Project2Entities db = new K22CNT3_NKL_2210900035_Project2Entities();

        // GET: STORies
        public ActionResult Index()
        {
            var sTORies = db.STORies.Include(s => s.NGUOI_DUNG);
            return View(sTORies.ToList());
        }

        // GET: STORies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STORY sTORY = db.STORies.Find(id);
            if (sTORY == null)
            {
                return HttpNotFound();
            }
            return View(sTORY);
        }

        // GET: STORies/Create
        public ActionResult Create()
        {
            ViewBag.nguoi_dang = new SelectList(db.NGUOI_DUNG, "ma_nguoi_dung", "ten_dang_nhap");
            return View();
        }

        // POST: STORies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ma_truyen,ten_truyen,tac_gia,the_loai,mo_ta,ngay_dang,nguoi_dang")] STORY sTORY)
        {
            if (ModelState.IsValid)
            {
                db.STORies.Add(sTORY);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.nguoi_dang = new SelectList(db.NGUOI_DUNG, "ma_nguoi_dung", "ten_dang_nhap", sTORY.nguoi_dang);
            return View(sTORY);
        }

        // GET: STORies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STORY sTORY = db.STORies.Find(id);
            if (sTORY == null)
            {
                return HttpNotFound();
            }
            ViewBag.nguoi_dang = new SelectList(db.NGUOI_DUNG, "ma_nguoi_dung", "ten_dang_nhap", sTORY.nguoi_dang);
            return View(sTORY);
        }

        // POST: STORies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ma_truyen,ten_truyen,tac_gia,the_loai,mo_ta,ngay_dang,nguoi_dang")] STORY sTORY)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sTORY).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.nguoi_dang = new SelectList(db.NGUOI_DUNG, "ma_nguoi_dung", "ten_dang_nhap", sTORY.nguoi_dang);
            return View(sTORY);
        }

        // GET: STORies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STORY sTORY = db.STORies.Find(id);
            if (sTORY == null)
            {
                return HttpNotFound();
            }
            return View(sTORY);
        }

        // POST: STORies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            STORY sTORY = db.STORies.Find(id);
            db.STORies.Remove(sTORY);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

backend/K22CNT3_NKL_2210900035_Project2/K22CNT3_NKL_2210900035_Project2/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT3_NKL_2210900035_Project2.Models;

namespace K22CNT3_NKL_2210900035_Project2.Controllers
{
    public class UserController : Controller
    {
        private K22CNT3_NKL_2210900035_Project2Entities db = new K22CNT3_NKL_2210900035_Project2Entities();

        // GET: User
        public ActionResult Index()
        {
            return View(db.NGUOI_DUNG.ToList());
        }

        // GET: User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NGUOI_DUNG nGUOI_DUNG = db.NGUOI_DUNG.Find(id);
            if (nGUOI_DUNG == null)
            {
                return HttpNotFound();
            }
            return View(nGUOI_DUNG);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ma_nguoi_dung,ten_dang_nhap,mat_khau,email,ngay_dang_ky")] NGUOI_DUNG nGUOI_DUNG)
        {
            if (ModelState.IsValid)
            {
                db.NGUOI_DUNG.Add(nGUOI_DUNG);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nGUOI_DUNG);
        }

        // GET: User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NGUOI_DUNG nGUOI_DUNG = db.NGUOI_DUNG.Find(id);
            if (nGUOI_DUNG == null)
            {
                return HttpNotFound();
            }
            return View(nGUOI_DUNG);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ma_nguoi_dung,ten_dang_nhap,mat_khau,email,ngay_dang_ky")] NGUOI_DUNG nGUOI_DUNG)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nGUOI_DUNG).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nGUOI_DUNG);
        }

        // GET: User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NGUOI_DUNG nGUOI_DUNG = db.NGUOI_DUNG.Find(id);
            if (nGUOI_DUNG == null)
            {
                return HttpNotFound();
            }
            return View(nGUOI_DUNG);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NGUOI_DUNG nGUOI_DUNG = db.NGUOI_DUNG.Find(id);
            db.NGUOI_DUNG.Remove(nGUOI_DUNG);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

backend/K22CNT3_NKL_2210900035_Project2/K22CNT3_NKL_2210900035_Project2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Quan lý web đọc truyện</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
<style>
      /* Cải thiện giao diện chung */
body {
    font-family: Arial, sans-serif;
    background-color: #f8f9fa;
    margin: 0;
    padding: 0;
    color: #333;
}

/* Navbar */
.navbar {
    background-color: #007bff;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.navbar .navbar-brand {
    color: #fff;
    font-size: 1.8rem;
    font-weight: 700;
    text-transform: uppercase;
    padding: 10px 15px;
}

.navbar .navbar-brand:hover {
    color: #fff;
    text-decoration: none;
    background-color: #0056b3;
    border-radius: 5px;
}

.navbar-nav .nav-link {
    color: #fff;
    font-size: 1.1rem;
    padding: 10px 20px;
    transition: background-color 0.3s ease, color 0.3s ease;
}

.navbar-nav .nav-link:hover {
    background-color: #0056b3;
    color: #fff;
    border-radius: 5px;
}

.navbar-toggler {
    border-color: #fff;
}

.navbar-toggler-icon {
    background-color: #fff;
}

/* Body content */
.container.body-content {
    padding: 40px 15px;
    max-width: 1200px;
    margin: 0 auto;
}

/* Footer */
footer {
    background-color: #343a40;
    color: #fff;
    padding: 20px 0;
    text-align: center;
    font-size: 1rem;
    box-shadow: 0 -2px 4px rgba(0, 0, 0, 0.1);
}

footer p {
    margin: 0;
}

/* Navbar responsive */


    .navbar-nav .nav-link {
        width: 100%;
        text-align: left;
        padding: 12px 20px;
    }

    .container.body-content {
        padding: 20px 10px;
    }


/* Thêm hiệu ứng hover cho navbar */
.navbar-nav {
    display: flex;
    justify-content: space-around;
    align-items: center;
    margin: 0;
}

.navbar-nav li {
    list-style-type: none;
}

/* Thêm hiệu ứng cho các liên kết */
.nav-link {
    display: inline-block;
    padding: 12px 20px;
    text-decoration: none;
    color: white;
    transition: background-color 0.3s ease, color 0.3s ease;
    border-radius: 5px;
    margin: 5px 0;
}

.nav-link:hover {
    background-color: #0056b3;
    color: white;
}

/* Tăng cường bố cục và thẩm mỹ cho các nút */
.btn {
    transition: background-color 0.3s ease, color 0.3s ease;
    border-radius: 5px;
    padding: 10px 20px;
}

.btn:hover {
    background-color: #0056b3;
    color: white;
}


</style>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Quan lý web đọc truyện", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("Admin", "Index", "QUAN_TRI", new { area = "" }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("Quản lý thành viên", "Index", "User", new { area = "" }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("Quản lý truyện", "Index", "STORies", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Quản lý chương truyện", "Index", "CHAPTERs", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Quản lý bình luận", "Index", "COMMENTs", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>