backend/K22CNT3_NKL_2210900035_Project2/K22CNT3_NKL_2210900035_Project2/Controllers/CHAPTERsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT3_NKL_2210900035_Project2.Models;

namespace K22CNT3_NKL_2210900035_Project2.Controllers
{
    public class CHAPTERsController : Controller
    {
        private K22CNT3_NKL_2210900035_Project2Entities db = new K22CNT3_NKL_2210900035_Project2Entities();

        // GET: CHAPTERs
        public ActionResult Index()
        {
            var cHAPTERs = db.CHAPTERs.Include(c => c.STORY);
            return View(cHAPTERs.ToList());
        }

        // GET: CHAPTERs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CHAPTER cHAPTER = db.CHAPTERs.Find(id);
            if (cHAPTER == null)
            {
                return HttpNotFound();
            }
            return View(cHAPTER);
        }

        // GET: CHAPTERs/Create
        public ActionResult Create()
        {
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen");
            return View();
        }

        // POST: CHAPTERs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ma_chuong,so_chuong,ten_chuong,noi_dung,ngay_dang,ma_truyen")] CHAPTER cHAPTER)
        {
            if (ModelState.IsValid)
            {
                db.CHAPTERs.Add(cHAPTER);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen", cHAPTER.ma_truyen);
            return View(cHAPTER);
        }

        // GET: CHAPTERs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CHAPTER cHAPTER = db.CHAPTERs.Find(id);
            if (cHAPTER == null)
            {
                return HttpNotFound();
            }
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen", cHAPTER.ma_truyen);
            return View(cHAPTER);
        }

        // POST: CHAPTERs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ma_chuong,so_chuong,ten_chuong,noi_dung,ngay_dang,ma_truyen")] CHAPTER cHAPTER)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cHAPTER).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen", cHAPTER.ma_truyen);
            return View(cHAPTER);
        }

        // GET: CHAPTERs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CHAPTER cHAPTER = db.CHAPTERs.Find(id);
            if (cHAPTER == null)
            {
                return HttpNotFound();
            }
            return View(cHAPTER);
        }

        // POST: CHAPTERs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CHAPTER cHAPTER = db.CHAPTERs.Find(id);
            db.CHAPTERs.Remove(cHAPTER);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

backend/K22CNT3_NKL_2210900035_Project2/K22CNT3_NKL_2210900035_Project2/Controllers/COMMENTsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT3_NKL_2210900035_Project2.Models;

namespace K22CNT3_NKL_2210900035_Project2.Controllers
{
    public class COMMENTsController : Controller
    {
        private K22CNT3_NKL_2210900035_Project2Entities db = new K22CNT3_NKL_2210900035_Project2Entities();

        // GET: COMMENTs
        public ActionResult Index()
        {
            var cOMMENTs = db.COMMENTs.Include(c => c.NGUOI_DUNG).Include(c => c.STORY);
            return View(cOMMENTs.ToList());
        }

        // GET: COMMENTs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COMMENT cOMMENT = db.COMMENTs.Find(id);
            if (cOMMENT == null)
            {
                return HttpNotFound();
            }
            return View(cOMMENT);
        }

        // GET: COMMENTs/Create
        public ActionResult Create()
        {
            ViewBag.ma_nguoi_dung = new SelectList(db.NGUOI_DUNG, "ma_nguoi_dung", "ten_dang_nhap");
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen");
            return View();
        }

        // POST: COMMENTs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ma_binh_luan,noi_dung,ngay_binh_luan,ma_nguoi_dung,ma_truyen")] COMMENT cOMMENT)
        {
            if (ModelState.IsValid)
            {
                db.COMMENTs.Add(cOMMENT);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ma_nguoi_dung = new SelectList(db.NGUOI_DUNG, "ma_nguoi_dung", "ten_dang_nhap", cOMMENT.ma_nguoi_dung);
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen", cOMMENT.ma_truyen);
            return View(cOMMENT);
        }

        // GET: COMMENTs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COMMENT cOMMENT = db.COMMENTs.Find(id);
            if (cOMMENT == null)
            {
                return HttpNotFound();
            }
            ViewBag.ma_nguoi_dung = new SelectList(db.NGUOI_DUNG, "ma_nguoi_dung", "ten_dang_nhap", cOMMENT.ma_nguoi_dung);
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen", cOMMENT.ma_truyen);
            return View(cOMMENT);
        }

        // POST: COMMENTs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ma_binh_luan,noi_dung,ngay_binh_luan,ma_nguoi_dung,ma_truyen")] COMMENT cOMMENT)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cOMMENT).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ma_nguoi_dung = new SelectList(db.NGUOI_DUNG, "ma_nguoi_dung", "ten_dang_nhap", cOMMENT.ma_nguoi_dung);
            ViewBag.ma_truyen = new SelectList(db.STORies, "ma_truyen", "ten_truyen", cOMMENT.ma_truyen);
            return View(cOMMENT);
        }

        // GET: COMMENTs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COMMENT cOMMENT = db.COMMENTs.Find(id);
            if (cOMMENT == null)
            {
                return HttpNotFound();
            }
            return View(cOMMENT);
        }

        // POST: COMMENTs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            COMMENT cOMMENT = db.COMMENTs.Find(id);
            db.COMMENTs.Remove(cOMMENT);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

backend/K22CNT3_NKL_2210900035_Project2/K22CNT3_NKL_2210900035_Project2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace K22CNT3_NKL_2210900035_Project2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

backend/K22CNT3_NKL_2210900035_Project2/K22CNT3_NKL_2210900035_Project2/Controllers/QUAN_TRIController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT3_NKL_2210900035_Project2.Models;

namespace K22CNT3_NKL_2210900035_Project2.Controllers
{
    public class QUAN_TRIController : Controller
    {
        private K22CNT3_NKL_2210900035_Project2Entities db = new K22CNT3_NKL_2210900035_Project2Entities();

        // GET: QUAN_TRI
        public ActionResult Index()
        {
            return View(db.QUAN_TRI.ToList());
        }

        // GET: QUAN_TRI/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QUAN_TRI qUAN_TRI = db.QUAN_TRI.Find(id);
            if (qUAN_TRI == null)
            {
                return HttpNotFound();
            }
            return View(qUAN_TRI);
        }

        // GET: QUAN_TRI/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QUAN_TRI/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ma_quan_tri,mat_khau,ten_dang_nhap,email,ngay_tao,trang_thai")] QUAN_TRI qUAN_TRI)
        {
            if (ModelState.IsValid)
            {
                db.QUAN_TRI.Add(qUAN_TRI);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(qUAN_TRI);
        }

        // GET: QUAN_TRI/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QUAN_TRI qUAN_TRI = db.QUAN_TRI.Find(id);
            if (qUAN_TRI == null)
            {
                return HttpNotFound();
            }
            return View(qUAN_TRI);
        }

        // POST: QUAN_TRI/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ma_quan_tri,mat_khau,ten_dang_nhap,email,ngay_tao,trang_thai")] QUAN_TRI qUAN_TRI)
        {
            if (ModelState.IsValid)
            {
                db.Entry(qUAN_TRI).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(qUAN_TRI);
        }

        // GET: QUAN_TRI/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QUAN_TRI qUAN_TRI = db.QUAN_TRI.Find(id);
            if (qUAN_TRI == null)
            {
                return HttpNotFound();
            }
            return View(qUAN_TRI);
        }

        // POST: QUAN_TRI/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QUAN_TRI qUAN_TRI = db.QUAN_TRI.Find(id);
            db.QUAN_TRI.Remove(qUAN_TRI);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

backend/K22CNT3_NKL_2210900035_Project2/K22CNT3_NKL_2210900035_Project2/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT3_NKL_2210900035_Project2.Models;

namespace K22CNT3_NKL_2210900035_Project2.Controllers
{
    public class UserController : Controller
    {
        private K22CNT3_NKL_2210900035_Project2Entities db = new K22CNT3_NKL_2210900035_Project2Entities();

        // GET: User
        public ActionResult Index()
        {
            return View(db.NGUOI_DUNG.ToList());
        }

        // GET: User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NGUOI_DUNG nGUOI_DUNG = db.NGUOI_DUNG.Find(id);
            if (nGUOI_DUNG == null)
            {
                return HttpNotFound();
            }
            return View(nGUOI_DUNG);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ma_nguoi_dung,ten_dang_nhap,mat_khau,email,ngay_dang_ky")] NGUOI_DUNG nGUOI_DUNG)
        {
            if (ModelState.IsValid)
            {
                db.NGUOI_DUNG.Add(nGUOI_DUNG);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nGUOI_DUNG);
        }

        // GET: User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NGUOI_DUNG nGUOI_DUNG = db.NGUOI_DUNG.Find(id);
            if (nGUOI_DUNG == null)
            {
                return HttpNotFound();
            }
            return View(nGUOI_DUNG);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ma_nguoi_dung,ten_dang_nhap,mat_khau,email,ngay_dang_ky")] NGUOI_DUNG nGUOI_DUNG)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nGUOI_DUNG).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nGUOI_DUNG);
        }

        // GET: User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NGUOI_DUNG nGUOI_DUNG = db.NGUOI_DUNG.Find(id);
            if (nGUOI_DUNG == null)
            {
                return HttpNotFound();
            }
            return View(nGUOI_DUNG);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NGUOI_DUNG nGUOI_DUNG = db.NGUOI_DUNG.Find(id);
            db.NGUOI_DUNG.Remove(nGUOI_DUNG);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

backend/K22CNT3_NKL_2210900035_Project2/K22CNT3_NKL_2210900035_Project2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

backend/K22CNT3_NKL_2210900035_Project2/K22CNT3_NKL_2210900035_Project2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

backend/K22CNT3_NKL_2210900035_Project2/K22CNT3_NKL_2210900035_Project2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang Quản Trị - Web Đọc Truyện";
}

<main>
    <!-- Chào mừng đến trang quản trị -->
    <section class="row" aria-labelledby="adminTitle">
        <h1 id="title" class="text-center">Chào Mừng Đến Trang Quản Trị</h1>
        <p class="lead text-center">Quản lý tất cả các phần trong hệ thống của Web Đọc Truyện tại đây. Dưới đây là các chức năng quản lý truyện, chương, người dùng, bình luận, và quản lý tài khoản admin.</p>
    </section>

    <div class="row">
        <!-- Section 1: Quản trị -->
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Quản Lý Tài Khoản Admin</h2>
            <p>
                Quản lý tài khoản của các Admin trên hệ thống, nơi bạn có thể thêm, chỉnh sửa hoặc xóa tài khoản quản trị viên.
            </p>
            <p><a class="btn btn-primary" href="@Url.Action("Index", "QUAN_TRI")">Quản Lý Admin &raquo;</a></p> <!-- Liên kết đến trang QUAN_TRI -->
        </section>

        <!-- Section 2: Quản lý người dùng -->
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Quản Lý Tài Khoản Người Dùng</h2>
            <p>
                Quản lý tài khoản người dùng trên nền tảng Web Đọc Truyện. Bạn có thể chỉnh sửa thông tin người dùng và theo dõi hoạt động của họ.
            </p>
            <p><a class="btn btn-success" href="@Url.Action("Index", "User")">Quản Lý Người Dùng &raquo;</a></p> <!-- Liên kết đến trang User -->
        </section>

        <!-- Section 3: Quản lý truyện -->
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Quản Lý Truyện</h2>
            <p>
                Khám phá và quản lý tất cả các câu chuyện trên trang web. Bạn có thể thêm, chỉnh sửa, hoặc xóa truyện.
            </p>
            <p><a class="btn btn-warning" href="@Url.Action("Index", "Stories")">Quản Lý Truyện &raquo;</a></p> <!-- Liên kết đến trang Stories -->
        </section>
    </div>

    <div class="row">
        <!-- Section 4: Quản lý chương -->
        <section class="col-md-4" aria-labelledby="chapterTitle">
            <h2 id="chapterTitle">Quản Lý Chương</h2>
            <p>
                Quản lý các chương của truyện, bạn có thể thêm, sửa hoặc xóa các chương trong mỗi truyện.
            </p>
            <p><a class="btn btn-info" href="@Url.Action("Index", "CHAPTERs")">Quản Lý Chương &raquo;</a></p> <!-- Liên kết đến trang CHAPTERs -->
        </section>

        <!-- Section 5: Quản lý bình luận -->
        <section class="col-md-4" aria-labelledby="commentTitle">
            <h2 id="commentTitle">Quản Lý Bình Luận</h2>
            <p>
                Theo dõi và quản lý các bình luận của người dùng. Bạn có thể duyệt qua và xóa các bình luận nếu cần thiết.
            </p>
            <p><a class="btn btn-danger" href="@Url.Action("Index", "COMMENTs")">Quản Lý Bình Luận &raquo;</a></p> <!-- Liên kết đến trang COMMENTs -->
        </section>
    </div>
</main>

<!-- CSS cho sinh động -->
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f8f9fa;
        color: #333;
    }

    #title {
        font-size: 2.5rem;
        color: #007bff;
        font-weight: 700;
        margin-top: 30px;
        margin-bottom: 20px;
    }

    .text-center {
        text-align: center;
    }

    .lead {
        font-size: 1.25rem;
        color: #555;
        margin-bottom: 30px;
    }

    .row {
        margin-top: 30px;
    }

    .col-md-4 {
        margin-bottom: 20px;
    }

    .section-title {
        color: #007bff;
        font-size: 1.75rem;
        font-weight: 600;
    }

    .btn {
        padding: 12px 25px;
        font-size: 1rem;
        text-decoration: none;
        border-radius: 5px;
        display: inline-block;
        width: 100%;
        text-align: center;
        margin-top: 10px;
    }

    .btn-primary {
        background-color: #007bff;
        color: white;
        transition: background-color 0.3s ease;
    }

        .btn-primary:hover {
            background-color: #0056b3;
        }

    .btn-success {
        background-color: #28a745;
        color: white;
        transition: background-color 0.3s ease;
    }

        .btn-success:hover {
            background-color: #218838;
        }

    .btn-warning {
        background-color: #ffc107;
        color: white;
        transition: background-color 0.3s ease;
    }

        .btn-warning:hover {
            background-color: #e0a800;
        }

    .btn-info {
        background-color: #17a2b8;
        color: white;
        transition: background-color 0.3s ease;
    }

        .btn-info:hover {
            background-color: #138496;
        }

    .btn-danger {
        background-color: #dc3545;
        color: white;
        transition: background-color 0.3s ease;
    }

        .btn-danger:hover {
            background-color: #c82333;
        }

    .row .col-md-4 {
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
    }

        .row .col-md-4:hover {
            box-shadow: 0 6px 10px rgba(0, 0, 0, 0.15);
            transition: box-shadow 0.3s ease-in-out;
        }
</style>